version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: yeasio-db
    restart: always
    environment:
      POSTGRES_USER: yeasio
      POSTGRES_PASSWORD: yeasio123
      POSTGRES_DB: yeasio_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
